ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profession" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "practiceArea" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasSecretary" BOOLEAN;
