ALTER TABLE "Clinic"
  ADD COLUMN IF NOT EXISTS "professionalOpeningTime" TEXT NOT NULL DEFAULT '09:00',
  ADD COLUMN IF NOT EXISTS "professionalClosingTime" TEXT NOT NULL DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS "professionalHourlyCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
